name:               "Quangdao Nguyen"
description:        "80% Robot"

url:                "https://www.quangdao.com"
author:             "thinker3197"
gravatar_hash:      ""
twitter:            "quangdaon"
email:              "quangdaon@gmail.com"
github:             "quangdaon"
linkedin:           "quangdaonguyen"

disqus_shortname:   "quangdao-nguyen"

background:         "/resources/images/side-background.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Projects"
    href:           "/projects"
  - name:           "Work"
    href:           "/portfolio"

collections:
  portfolio:
    sort_by: priority
    output: true
  projects:
    output: false
    
sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "portfolio"
    values:
        layout:     "portfolio"

gems:
  - jekyll-paginate