name:               "Quangdao Nguyen"
description:        "81.5% Robot"
default_meta:       "Creative, adaptable, and resourceful software engineer with a passion for pushing limits and challenging impossiblities."

url:                "https://www.quangdao.com"
author:             "thinker3197"
gravatar_hash:      ""
twitter:            "quangdaon"
email:              "me@quangdao.com"
github:             "quangdaon"
linkedin:           "quangdaonguyen"

disqus_shortname:   "quangdao-nguyen"

background:         "/resources/images/side-background.webp"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "My Work"
    href:           "/projects"

collections:
  portfolio:
    sort_by: priority
    output: true
  comics:
    sort_by: order
    output: true
    permalink: /:collection/:title
  projects:
    output: false
    
sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "portfolio"
    values:
        layout:     "portfolio"
  -
    scope:
      path:         ""
      type:         "comics"
    values:
        layout:     "comic"
plugins:
  - jekyll-paginate